---
- name: Base setup (proxy, cert, docker, images)
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure target is Ubuntu
      assert:
        that: ansible_distribution | lower == 'ubuntu'
        fail_msg: "This playbook supports Ubuntu only. Found {{ ansible_distribution }}."
        success_msg: "Ubuntu detected: {{ ansible_distribution_release }}"

  roles:
    - role: proxy
      tags: [ 'proxy', 'cert' ]
    - role: docker
      tags: [ 'docker' ]
    - role: images
      tags: [ 'images' ]
